#!/bin/bash 

# Welcome the user 
echo "Hello, $(whoami). Welcome!"

# Show the date and time
echo " ******************************* CURRENT DATE AND TIME ****************************** "
date | awk '{print " Today is: " $3 " - " $2 " ; Day = " $1 " ; Time: " $4 }'
echo ""

echo " *************************************** DISK SPACE AVAILABLE ********************************************************************** "
df -H | xargs | awk '{ print " Disk Space Available: " "Free/Used: " $10 "/" $9 " :GB" }'
echo ""

echo " ***************************** USER UPTIME ****************************************************** "
uptime
echo ""

echo "******************************* LAST 3 LOGIN DETAILS ********************************************* "
last | head -3
echo ""

echo "****************************************** CURRENTLY CONNECTED *************************************** "
w
